version: '3'
services:
  build:
    image: openjdk:12-jdk-alpine
    working_dir: '/project'
    volumes:
      - '.:/project'
      - '.docker/gradle-cache:/root/.gradle'
    command: ['./gradlew', '--info', build]
  api:
    image: openjdk:12-jdk-alpine
    working_dir: '/project'
    volumes:
      - '.:/project'
    environment:
      ZHT_CONFIG: .docker/config/config.properties
    links:
      - db
    depends_on:
      - db
    command: [sh, './.docker/scripts/launch.sh']
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: zht
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: zht
#      PGUSER: zht
#      PGPASSWORD: secret
#      PGDATABASE: zht
      PGDATA: /data
    volumes:
      - '.docker/postgres-data:/data'
