version: '3'
services:
  build:
    image: openjdk:12-jdk-alpine
    working_dir: '/project'
    volumes:
      - '.:/project'
      - '.docker/gradle-cache:/root/.gradle'
    command: ['./gradlew', '--info', build]
  api:
    image: openjdk:12-jdk-alpine
    working_dir: '/project'
    volumes:
      - '.:/project'
    environment:
      ZHT_CONFIG: .docker/config/test.properties
    ports:
      - '8080:8080'
    command: [sh, './.docker/scripts/launch.sh']

